### PR TITLE
Drop `lodash.indexOf`.

### LINKED ISSUE #4: Consider dropping `lodash.indexOf`.
It'd be a major bump, but it'd make `math-expression-evaluator` free of dependencies.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
Closes #4.

### CODE REVIEW

**Comment by ankitbug94** [comment]
> Array.prototype.indexOf()
> was added to the ECMA-262 standard in the 5th edition; as such it may not be present in all browsers. 

May you write the ponyfill instead means a function which takes two argument first is array and second is element and we wont have to change anything in the below code

**Comment by wtgtybhertgeghgtwtg** [comment]
I'm sorry, I don't understand.

**Comment by ankitbug94** [comment]
lodash.indexOf exports a function. right? So why not create our own function in second line of lexer.js

```javascript
var indexOf = function (arr, element) {
    //find and return the index 
    //not found then return the null
}
```
Do ask again if still I am not clear

**Comment by wtgtybhertgeghgtwtg** [comment]
That wouldn't be any different than importing `lodash.indexOf`.  I'm proposing using the native method.  It should work as far back as IE9.

**Comment by ankitbug94** [comment]
Why leave IE8 for this trivial thing ;). And this would be different as in theory we are going to include the `lodash.indexof` code in our code, hence removing the dependency. Just what you asked for

**Comment by wtgtybhertgeghgtwtg** [comment]
Microsoft hasn't supported IE8 for over a year now.  If the user needs IE8 support, they can always user the older version.

**Comment by ankitbug94** [comment]
Ah! It looks convincing. Update the changelog in readme please

**Comment by wtgtybhertgeghgtwtg** [comment]
There is no changelog in the readme.

**Comment by ankitbug94** [comment]
Yep! Because I didn't need to maintain it. But since now it is used by cssnano etc., I think it is necessary. Don't worry. Rest I will do.

**Pull request merged**
